export const SET_ALL_STATIC_DATA = 'SET_ALL_STATIC_DATA';
export const UPDATE_STATIC_DATA = 'UPDATE_STATIC_DATA';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const UPDATE_ROUTE_DETAILS = 'UPDATE_ROUTE_DETAILS';
export const SET_CURRENT_ENGAGEMENT = 'SET_CURRENT_ENGAGEMENT';
export const UPDATE_CURRENT_ENGAGEMENT = 'UPDATE_CURRENT_ENGAGEMENT';
export const RESET_CURRENT_ENGAGEMENT = 'RESET_CURRENT_ENGAGEMENT';
